### ISSUE TITLE
best gui to manage mongo

### ISSUE THREAD

**Issue by gedw99** [damianiandrea/mongodb-nats-connector#2]
hey @damianiandrea 

can you suggest a simple and easy to run GUi for mongo ? Like Pgadmin but for mongo.

just to make it easier to debug it etc :)

**Comment by damianiandrea** [comment]
Hi @gedw99,

I use Mongo Compass and Mongo Shell, check them out.

**Comment by gedw99** [comment]
Thanks dude !!
